---
version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"

    schedule:
      interval: "weekly"

    groups:
      vim:
        patterns:
          - "vimfiles/*"
      zsh:
        patterns:
          - "oh-my-zsh-custom/*"

  - package-ecosystem: "github-actions"
    directory: "/"

    schedule:
      interval: "weekly"
